version: '3.3'
services:
    redis:
        container_name: redis
        networks:
          - backend
        image: redis
    postgres:
        container_name: db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - postgres:/var/lib/postgresql/data
        networks: 
          - backend
        image: postgres
    result:
        ports:
            - '5001:80'
        container_name: result
        networks: 
          - backend
          - frontend
        volumes:
            - result:/app
        image: result
    vote:
        ports:
            - '5000:80'
        container_name: vote
        networks: 
          - backend
          - frontend
        volumes:
            - vote:/app
        image: vote
    worker:
        container_name: worker
        networks: 
          - backend
        image: worker
networks:
  backend:
    external: true
  frontend:
    external: true
volumes:
  postgres:
    external: true
  result:
    external: true
  vote:
    external: true
